#端口设置
server:
  port: 8012

spring:
  application:
    name: hyproject
  #redis cluster， 按照这种格式 StringRedisTemplate自动加载配置， jedisCluster需要配置
  redis:
    cluster:
      nodes:
        - 127.0.0.1:7000
        - 127.0.0.1:7001
        - 127.0.0.1:7002
        - 127.0.0.1:7003
        - 127.0.0.1:7004
        - 127.0.0.1:7005

#    single redis, 按照这种格式 StringRedisTemplate自动加载配置
#    redis:
#      host: 127.0.0.1
#      port: 8400


#  datasource:
#    url: jdbc:mysql://localhost:3306/mybatisTest
#    username: root
#    password: huangyue03
#    driverClassName: com.mysql.jdbc.Driver
#  jpa:
#    database: MYSQL
#    show-sql: true

#  cloud:
#    zookeeper:
#      enabled: true
#      connect-string: 127.0.0.1:2181,127.0.0.1:2182,127.0.0.1:2183
#    config:
#      enabled: false
#    discovery:
#      register: false

#custom config
custom:
  zk:
    connectString: 127.0.0.1:2181,127.0.0.1:2182,127.0.0.1:2183
    leaderPath: /hyproject/leader




